# Generated by Django 5.0.4 on 2024-05-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='1593cb', max_length=6),
        ),
    ]
